server:
  port: 8888

spring:
  application:
    name: ccw-config-service

  profiles:
    active: prod

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Puskin2911/ccw-config
          skip-ssl-validation: true
          search-paths:
            - ccw-config-prod